typography_spectrum: 0.0019407198570742465
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.8606827453109851
  lightness: 0.48618628293303495
  saturation: 0.3077713716678358
  rhythmicContrast: 0.7759874537032061
layout_spectrum: 0.5945496240479521
name: Kosner Burstein
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: New & Polished!
    id: 4cb229a8-2e42-4618-b10f-15c342486538
    type: content
  - name: High Holy Days
    id: fa4f050f-f2a8-45b5-b31c-56ab2341f4e0
    type: content
  - name: The Designer...
    id: 0966385e-f142-4409-a59c-368f26bc5eaa
    type: content
title: Kosner Burstein
content: []
coverPrefs:
  filter: false
description: The official Kosner Burstein website.
purpose:
  - type: external
    url: 'http://lk.kbf.am'
    label: Luke
  - type: external
    url: 'http://db.kbf.am'
    label: Diane
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3e44dc40-e662-4744-bb34-9d8f86f9abaa.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cbea1bf0-105b-4627-80b0-29013bb81aa8.png
github: true
analytics:
  google: UA-104323546-1
